export const PALETTES = [
  {
    id: "slate",
    name: "Health & Luxury",
    tagline: "Deep navy + champagne gold · quiet luxury",
    swatch: ["#22344F", "#B0A584", "#CFCBC0", "#E4E2DC", "#FBFAF6"],
    vars: {
      "--nv-bg": "#F4F3EF",
      "--nv-surface": "#FFFFFF",
      "--nv-surface-2": "#EFEEE8",
      "--nv-ink": "#22344F",
      "--nv-ink-panel": "#22344F",
      "--nv-primary": "#22344F",
      "--nv-primary-deep": "#1A2A42",
      "--nv-accent": "#B0A584",
      "--nv-line": "#E4E2DC",
      "--nv-line-strong": "#D6D2C8",
      "--nv-muted": "#5E6573",
      "--nv-on-primary": "#FBFAF6",
      "--nv-on-panel": "#E4E2DC",
    },
  },
  {
    id: "emerald-gold",
    name: "Emerald & Gold",
    tagline: "Emerald green + gold buttons · health & luxury",
    swatch: ["#173D2E", "#8A6E22", "#C6AE73", "#E0DBCB", "#F5F2EA"],
    vars: {
      "--nv-bg": "#F5F2EA",
      "--nv-surface": "#FFFFFF",
      "--nv-surface-2": "#ECE7DA",
      "--nv-ink": "#173D2E",
      "--nv-ink-panel": "#143527",
      "--nv-primary": "#8A6E22",
      "--nv-primary-deep": "#6F571A",
      "--nv-accent": "#C6AE73",
      "--nv-line": "#E6E1D2",
      "--nv-line-strong": "#D7D0BC",
      "--nv-muted": "#586056",
      "--nv-on-primary": "#FBF8EE",
      "--nv-on-panel": "#E7E3D2",
    },
  },
  {
    id: "midnight-champagne",
    name: "Midnight & Champagne",
    tagline: "Deep midnight navy + classic champagne",
    swatch: ["#0B193B", "#1D2C54", "#CDBA89", "#D6D3C8", "#F1EFEA"],
    vars: {
      "--nv-bg": "#F1EFEA",
      "--nv-surface": "#FFFFFF",
      "--nv-surface-2": "#E8E6DF",
      "--nv-ink": "#0B193B",
      "--nv-ink-panel": "#0B193B",
      "--nv-primary": "#1D2C54",
      "--nv-primary-deep": "#131F3D",
      "--nv-accent": "#CDBA89",
      "--nv-line": "#E4E2DA",
      "--nv-line-strong": "#D6D3C8",
      "--nv-muted": "#5A6172",
      "--nv-on-primary": "#F1EFEA",
      "--nv-on-panel": "#DDE2EC",
    },
  },
  {
    id: "indigo-sand",
    name: "Indigo & Sand",
    tagline: "Royal indigo + warm sand",
    swatch: ["#1A284D", "#223974", "#D9BF9C", "#D6D4CE", "#F1F0EE"],
    vars: {
      "--nv-bg": "#F1F0EE",
      "--nv-surface": "#FFFFFF",
      "--nv-surface-2": "#E8E7E3",
      "--nv-ink": "#1A284D",
      "--nv-ink-panel": "#1A284D",
      "--nv-primary": "#223974",
      "--nv-primary-deep": "#182B5A",
      "--nv-accent": "#D9BF9C",
      "--nv-line": "#E5E3DF",
      "--nv-line-strong": "#D6D4CE",
      "--nv-muted": "#5C6273",
      "--nv-on-primary": "#F2F0EC",
      "--nv-on-panel": "#DEE3EE",
    },
  },
  {
    id: "steel-wheat",
    name: "Steel & Wheat",
    tagline: "Steel blue + wheat gold",
    swatch: ["#204164", "#265688", "#D5C5AD", "#D7D2C6", "#F4F1EB"],
    vars: {
      "--nv-bg": "#F4F1EB",
      "--nv-surface": "#FFFFFF",
      "--nv-surface-2": "#ECE8DF",
      "--nv-ink": "#204164",
      "--nv-ink-panel": "#18334F",
      "--nv-primary": "#265688",
      "--nv-primary-deep": "#1D4369",
      "--nv-accent": "#D5C5AD",
      "--nv-line": "#E6E2D9",
      "--nv-line-strong": "#D7D2C6",
      "--nv-muted": "#5C6675",
      "--nv-on-primary": "#F3F1EB",
      "--nv-on-panel": "#DCE5EF",
    },
  },
  {
    id: "azure-cream",
    name: "Azure & Cream",
    tagline: "Bright azure + soft cream",
    swatch: ["#125484", "#4F88CC", "#ECD8C0", "#D5D4D0", "#F3F3F1"],
    vars: {
      "--nv-bg": "#F3F3F1",
      "--nv-surface": "#FFFFFF",
      "--nv-surface-2": "#EAEAE8",
      "--nv-ink": "#123A5C",
      "--nv-ink-panel": "#103450",
      "--nv-primary": "#125484",
      "--nv-primary-deep": "#0E4068",
      "--nv-accent": "#ECD8C0",
      "--nv-line": "#E5E4E1",
      "--nv-line-strong": "#D5D4D0",
      "--nv-muted": "#5C6470",
      "--nv-on-primary": "#EFF3F6",
      "--nv-on-panel": "#D7E3EE",
    },
  },
  {
    id: "harbor-biscuit",
    name: "Harbor Blue & Biscuit",
    tagline: "Classic harbor blue + biscuit gold",
    swatch: ["#152B64", "#356094", "#EED9B4", "#D6D6D2", "#F4F4F3"],
    vars: {
      "--nv-bg": "#F4F4F3",
      "--nv-surface": "#FFFFFF",
      "--nv-surface-2": "#EBEBEA",
      "--nv-ink": "#152B64",
      "--nv-ink-panel": "#11224F",
      "--nv-primary": "#356094",
      "--nv-primary-deep": "#294B73",
      "--nv-accent": "#EED9B4",
      "--nv-line": "#E6E5E2",
      "--nv-line-strong": "#D6D6D2",
      "--nv-muted": "#5C6474",
      "--nv-on-primary": "#F2F4F7",
      "--nv-on-panel": "#DCE4EF",
    },
  },
  {
    id: "brass",
    name: "Cream & Brass",
    tagline: "Navy + brass-orange on warm cream · editorial",
    swatch: ["#1B2733", "#2E4257", "#C27A26", "#DAD6CC", "#F1EEE5"],
    vars: {
      "--nv-bg": "#F1EEE5",
      "--nv-surface": "#FBFAF5",
      "--nv-surface-2": "#E9E5D9",
      "--nv-ink": "#1E2A36",
      "--nv-ink-panel": "#1B2733",
      "--nv-primary": "#2E4257",
      "--nv-primary-deep": "#233544",
      "--nv-accent": "#C27A26",
      "--nv-line": "#E3DFD3",
      "--nv-line-strong": "#D3CDBE",
      "--nv-muted": "#66625A",
      "--nv-on-primary": "#F4F1EA",
      "--nv-on-panel": "#E7E2D6",
    },
  },
  {
    id: "aubergine",
    name: "Aubergine & Platinum",
    tagline: "Moody · modern · regal",
    swatch: ["#241726", "#4A2E4E", "#7A5C7E", "#B8A9BE", "#E9E4EC"],
    vars: {
      "--nv-bg": "#F4F0F6",
      "--nv-surface": "#FBF8FC",
      "--nv-surface-2": "#ECE5F0",
      "--nv-ink": "#241726",
      "--nv-ink-panel": "#241726",
      "--nv-primary": "#4A2E4E",
      "--nv-primary-deep": "#321F35",
      "--nv-accent": "#7A5C7E",
      "--nv-line": "#E6DEEA",
      "--nv-line-strong": "#D6C9DC",
      "--nv-muted": "#6E5F72",
      "--nv-on-primary": "#F3ECF5",
      "--nv-on-panel": "#E9E4EC",
    },
  },
  {
    id: "camel",
    name: "Camel & Cream",
    tagline: "Quiet 'old money' neutrals",
    swatch: ["#7A6248", "#A88B66", "#C9B596", "#E6DAC6", "#F7F2E9"],
    vars: {
      "--nv-bg": "#F7F2E9",
      "--nv-surface": "#FFFDF8",
      "--nv-surface-2": "#F0E7D6",
      "--nv-ink": "#3D3023",
      "--nv-ink-panel": "#2A2117",
      "--nv-primary": "#7A6248",
      "--nv-primary-deep": "#5E4A35",
      "--nv-accent": "#A88B66",
      "--nv-line": "#E9DEC9",
      "--nv-line-strong": "#DACBB0",
      "--nv-muted": "#7C6E58",
      "--nv-on-primary": "#F9F4EA",
      "--nv-on-panel": "#EFE6D5",
    },
  },
  {
    id: "graphite",
    name: "Graphite & Chrome",
    tagline: "Sleek tech luxe",
    swatch: ["#15171A", "#2C3036", "#565C64", "#9AA1A9", "#E4E7EA"],
    vars: {
      "--nv-bg": "#F4F5F7",
      "--nv-surface": "#FFFFFF",
      "--nv-surface-2": "#EBEDF0",
      "--nv-ink": "#15171A",
      "--nv-ink-panel": "#15171A",
      "--nv-primary": "#2C3036",
      "--nv-primary-deep": "#15171A",
      "--nv-accent": "#565C64",
      "--nv-line": "#E2E5E9",
      "--nv-line-strong": "#CFD3D9",
      "--nv-muted": "#565C64",
      "--nv-on-primary": "#F4F5F7",
      "--nv-on-panel": "#E4E7EA",
    },
  },
  {
    id: "sage",
    name: "Sage & Clay",
    tagline: "Soft sage + clay · natural wellness",
    swatch: ["#2C3A2E", "#54664F", "#B07B5A", "#CBC9BC", "#F3F1E9"],
    vars: {
      "--nv-bg": "#F3F1E9",
      "--nv-surface": "#FFFFFF",
      "--nv-surface-2": "#ECEAE0",
      "--nv-ink": "#2C3A2E",
      "--nv-ink-panel": "#2C3A2E",
      "--nv-primary": "#54664F",
      "--nv-primary-deep": "#3F4E3C",
      "--nv-accent": "#B07B5A",
      "--nv-line": "#E4E1D6",
      "--nv-line-strong": "#D4D0C1",
      "--nv-muted": "#6B6B5E",
      "--nv-on-primary": "#F5F3EB",
      "--nv-on-panel": "#E2E5DC",
    },
  },
  {
    id: "midnight",
    name: "Midnight & Sky",
    tagline: "Midnight navy + sky · trusted clinical",
    swatch: ["#18253E", "#21304E", "#6E93C0", "#C6D2E0", "#F3F5F8"],
    vars: {
      "--nv-bg": "#F3F5F8",
      "--nv-surface": "#FFFFFF",
      "--nv-surface-2": "#E9EEF3",
      "--nv-ink": "#18253E",
      "--nv-ink-panel": "#18253E",
      "--nv-primary": "#21304E",
      "--nv-primary-deep": "#172339",
      "--nv-accent": "#6E93C0",
      "--nv-line": "#E0E5EC",
      "--nv-line-strong": "#CCD5DF",
      "--nv-muted": "#5C6675",
      "--nv-on-primary": "#F2F5F9",
      "--nv-on-panel": "#DDE6F0",
    },
  },
  {
    id: "plum",
    name: "Plum & Blush",
    tagline: "Deep plum + blush · refined care",
    swatch: ["#2E1E2A", "#4A2E42", "#C58E96", "#D9CBD1", "#F6F1F2"],
    vars: {
      "--nv-bg": "#F6F1F2",
      "--nv-surface": "#FFFFFF",
      "--nv-surface-2": "#EFE7EA",
      "--nv-ink": "#2E1E2A",
      "--nv-ink-panel": "#2E1E2A",
      "--nv-primary": "#4A2E42",
      "--nv-primary-deep": "#3A2434",
      "--nv-accent": "#C58E96",
      "--nv-line": "#E8DEE2",
      "--nv-line-strong": "#D8CAD0",
      "--nv-muted": "#6E5F67",
      "--nv-on-primary": "#F5EEF1",
      "--nv-on-panel": "#ECE0E5",
    },
  },
  {
    id: "teal",
    name: "Teal & Sand",
    tagline: "Deep teal + warm sand · modern medical",
    swatch: ["#143C43", "#1E5862", "#C9B393", "#C8D2CD", "#F1F4F2"],
    vars: {
      "--nv-bg": "#F1F4F2",
      "--nv-surface": "#FFFFFF",
      "--nv-surface-2": "#E7EDEA",
      "--nv-ink": "#143C43",
      "--nv-ink-panel": "#143C43",
      "--nv-primary": "#1E5862",
      "--nv-primary-deep": "#15434B",
      "--nv-accent": "#C9B393",
      "--nv-line": "#DDE4E0",
      "--nv-line-strong": "#CBD5CF",
      "--nv-muted": "#5C6B68",
      "--nv-on-primary": "#F0F4F2",
      "--nv-on-panel": "#D7E4E0",
    },
  },
  {
    id: "oxblood",
    name: "Oxblood & Bone",
    tagline: "Deep wine red + muted gold · prestige",
    swatch: ["#3A1820", "#6E2435", "#B08D55", "#D8CCBE", "#F5F1EC"],
    vars: {
      "--nv-bg": "#F5F1EC",
      "--nv-surface": "#FFFFFF",
      "--nv-surface-2": "#EEE7DF",
      "--nv-ink": "#3A1820",
      "--nv-ink-panel": "#3A1820",
      "--nv-primary": "#6E2435",
      "--nv-primary-deep": "#551B29",
      "--nv-accent": "#B08D55",
      "--nv-line": "#E7DFD6",
      "--nv-line-strong": "#D8CCBE",
      "--nv-muted": "#6E5A55",
      "--nv-on-primary": "#F6EEE9",
      "--nv-on-panel": "#E9D9D0",
    },
  },
  {
    id: "charcoal",
    name: "Charcoal & Gold",
    tagline: "Near-black + warm gold · luxe monochrome",
    swatch: ["#1C1B19", "#2B2A27", "#C2A24E", "#D3D0C8", "#F4F3F1"],
    vars: {
      "--nv-bg": "#F4F3F1",
      "--nv-surface": "#FFFFFF",
      "--nv-surface-2": "#EAE8E4",
      "--nv-ink": "#1C1B19",
      "--nv-ink-panel": "#1C1B19",
      "--nv-primary": "#2B2A27",
      "--nv-primary-deep": "#1C1B19",
      "--nv-accent": "#C2A24E",
      "--nv-line": "#E4E2DD",
      "--nv-line-strong": "#D3D0C8",
      "--nv-muted": "#615F58",
      "--nv-on-primary": "#F3F1EA",
      "--nv-on-panel": "#E6E2D6",
    },
  },
  {
    id: "cobalt",
    name: "Cobalt & Copper",
    tagline: "Clean cobalt blue + copper · confident",
    swatch: ["#14213D", "#20407E", "#C77B4B", "#CAD4E3", "#F2F4F8"],
    vars: {
      "--nv-bg": "#F2F4F8",
      "--nv-surface": "#FFFFFF",
      "--nv-surface-2": "#E8ECF3",
      "--nv-ink": "#14213D",
      "--nv-ink-panel": "#14213D",
      "--nv-primary": "#20407E",
      "--nv-primary-deep": "#182F5E",
      "--nv-accent": "#C77B4B",
      "--nv-line": "#DFE5EF",
      "--nv-line-strong": "#CAD4E3",
      "--nv-muted": "#5A6479",
      "--nv-on-primary": "#F1F4FA",
      "--nv-on-panel": "#D8E1F0",
    },
  },
  {
    id: "steel",
    name: "Steel & Rose",
    tagline: "Soft steel blue + dusty rose · calm modern",
    swatch: ["#2B313A", "#44505E", "#C08A86", "#D2D2D7", "#F4F3F4"],
    vars: {
      "--nv-bg": "#F4F3F4",
      "--nv-surface": "#FFFFFF",
      "--nv-surface-2": "#EAE9EC",
      "--nv-ink": "#2B313A",
      "--nv-ink-panel": "#2B313A",
      "--nv-primary": "#44505E",
      "--nv-primary-deep": "#333D49",
      "--nv-accent": "#C08A86",
      "--nv-line": "#E4E3E6",
      "--nv-line-strong": "#D2D2D7",
      "--nv-muted": "#62656D",
      "--nv-on-primary": "#F3F1F1",
      "--nv-on-panel": "#DEE2E7",
    },
  },
  {
    id: "mocha",
    name: "Mocha & Honey",
    tagline: "Warm mocha brown + honey · cozy spa luxe",
    swatch: ["#2E2118", "#5A4231", "#C99A4E", "#DACDB8", "#F5F1EA"],
    vars: {
      "--nv-bg": "#F5F1EA",
      "--nv-surface": "#FFFDF9",
      "--nv-surface-2": "#EEE6D9",
      "--nv-ink": "#2E2118",
      "--nv-ink-panel": "#2E2118",
      "--nv-primary": "#5A4231",
      "--nv-primary-deep": "#443124",
      "--nv-accent": "#C99A4E",
      "--nv-line": "#E8DECF",
      "--nv-line-strong": "#DACDB8",
      "--nv-muted": "#75665A",
      "--nv-on-primary": "#F6EFE4",
      "--nv-on-panel": "#EADCCB",
    },
  },
];


export const TYPOGRAPHIES = [
  {
    id: "grotesk",
    name: "Grotesk Modern",
    sample: "Aa",
    note: "Hanken Grotesk · IBM Plex Mono",
    vars: {
      "--nv-font-display": "'Hanken Grotesk', system-ui, sans-serif",
      "--nv-font-body": "'Hanken Grotesk', system-ui, sans-serif",
      "--nv-font-mono": "'IBM Plex Mono', ui-monospace, monospace",
      "--nv-display-tracking": "-0.032em",
    },
  },
  {
    id: "luxe",
    name: "Luxe Sans",
    sample: "Aa",
    note: "Poppins · Montserrat",
    vars: {
      "--nv-font-display": "'Poppins', system-ui, sans-serif",
      "--nv-font-body": "'Montserrat', system-ui, sans-serif",
      "--nv-font-mono": "'Montserrat', ui-monospace, monospace",
      "--nv-display-tracking": "-0.03em",
    },
  },
  {
    id: "editorial",
    name: "Editorial Serif",
    sample: "Aa",
    note: "Fraunces · Inter",
    vars: {
      "--nv-font-display": "'Fraunces', Georgia, 'Times New Roman', serif",
      "--nv-font-body": "'Inter', system-ui, sans-serif",
      "--nv-font-mono": "'IBM Plex Mono', ui-monospace, monospace",
      "--nv-display-tracking": "-0.02em",
    },
  },
  {
    id: "geometric",
    name: "Geometric Luxe",
    sample: "Aa",
    note: "Space Grotesk · Space Mono",
    vars: {
      "--nv-font-display": "'Space Grotesk', system-ui, sans-serif",
      "--nv-font-body": "'Space Grotesk', system-ui, sans-serif",
      "--nv-font-mono": "'Space Mono', ui-monospace, monospace",
      "--nv-display-tracking": "-0.03em",
    },
  },
  {
    id: "classic",
    name: "Classic Refined",
    sample: "Aa",
    note: "Playfair Display · DM Sans",
    vars: {
      "--nv-font-display": "'Playfair Display', Georgia, serif",
      "--nv-font-body": "'DM Sans', system-ui, sans-serif",
      "--nv-font-mono": "'IBM Plex Mono', ui-monospace, monospace",
      "--nv-display-tracking": "-0.02em",
    },
  },
  {
    id: "inter",
    name: "Clinical Inter",
    sample: "Aa",
    note: "Inter · IBM Plex Mono",
    vars: {
      "--nv-font-display": "'Inter', system-ui, sans-serif",
      "--nv-font-body": "'Inter', system-ui, sans-serif",
      "--nv-font-mono": "'IBM Plex Mono', ui-monospace, monospace",
      "--nv-display-tracking": "-0.02em",
    },
  },
  {
    id: "opensans",
    name: "Open Humanist",
    sample: "Aa",
    note: "Open Sans · IBM Plex Mono",
    vars: {
      "--nv-font-display": "'Open Sans', system-ui, sans-serif",
      "--nv-font-body": "'Open Sans', system-ui, sans-serif",
      "--nv-font-mono": "'IBM Plex Mono', ui-monospace, monospace",
      "--nv-display-tracking": "-0.015em",
    },
  },
  {
    id: "lato",
    name: "Friendly Lato",
    sample: "Aa",
    note: "Lato · IBM Plex Mono",
    vars: {
      "--nv-font-display": "'Lato', system-ui, sans-serif",
      "--nv-font-body": "'Lato', system-ui, sans-serif",
      "--nv-font-mono": "'IBM Plex Mono', ui-monospace, monospace",
      "--nv-display-tracking": "-0.015em",
    },
  },
  {
    id: "roboto",
    name: "Roboto",
    sample: "Aa",
    note: "Roboto · Roboto Mono",
    vars: {
      "--nv-font-display": "'Roboto', system-ui, sans-serif",
      "--nv-font-body": "'Roboto', system-ui, sans-serif",
      "--nv-font-mono": "'Roboto Mono', ui-monospace, monospace",
      "--nv-display-tracking": "-0.02em",
    },
  },
  {
    id: "arial",
    name: "Arial",
    sample: "Aa",
    note: "Arial · system mono",
    vars: {
      "--nv-font-display": "Arial, Helvetica, sans-serif",
      "--nv-font-body": "Arial, Helvetica, sans-serif",
      "--nv-font-mono": "ui-monospace, 'Cascadia Code', 'Segoe UI Mono', monospace",
      "--nv-display-tracking": "-0.01em",
    },
  },
  {
    id: "nunito",
    name: "Friendly Nunito",
    sample: "Aa",
    note: "Nunito · IBM Plex Mono",
    vars: {
      "--nv-font-display": "'Nunito', system-ui, sans-serif",
      "--nv-font-body": "'Nunito', system-ui, sans-serif",
      "--nv-font-mono": "'IBM Plex Mono', ui-monospace, monospace",
      "--nv-display-tracking": "-0.015em",
    },
  },
  {
    id: "manrope",
    name: "Modern Manrope",
    sample: "Aa",
    note: "Manrope · IBM Plex Mono",
    vars: {
      "--nv-font-display": "'Manrope', system-ui, sans-serif",
      "--nv-font-body": "'Manrope', system-ui, sans-serif",
      "--nv-font-mono": "'IBM Plex Mono', ui-monospace, monospace",
      "--nv-display-tracking": "-0.02em",
    },
  },
  {
    id: "worksans",
    name: "Clean Work Sans",
    sample: "Aa",
    note: "Work Sans · IBM Plex Mono",
    vars: {
      "--nv-font-display": "'Work Sans', system-ui, sans-serif",
      "--nv-font-body": "'Work Sans', system-ui, sans-serif",
      "--nv-font-mono": "'IBM Plex Mono', ui-monospace, monospace",
      "--nv-display-tracking": "-0.018em",
    },
  },
  {
    id: "sourcesans",
    name: "Source Humanist",
    sample: "Aa",
    note: "Source Sans 3 · IBM Plex Mono",
    vars: {
      "--nv-font-display": "'Source Sans 3', system-ui, sans-serif",
      "--nv-font-body": "'Source Sans 3', system-ui, sans-serif",
      "--nv-font-mono": "'IBM Plex Mono', ui-monospace, monospace",
      "--nv-display-tracking": "-0.015em",
    },
  },
  {
    id: "jakarta",
    name: "Premium Jakarta",
    sample: "Aa",
    note: "Plus Jakarta Sans · IBM Plex Mono",
    vars: {
      "--nv-font-display": "'Plus Jakarta Sans', system-ui, sans-serif",
      "--nv-font-body": "'Plus Jakarta Sans', system-ui, sans-serif",
      "--nv-font-mono": "'IBM Plex Mono', ui-monospace, monospace",
      "--nv-display-tracking": "-0.02em",
    },
  },
  {
    id: "mulish",
    name: "Light Mulish",
    sample: "Aa",
    note: "Mulish · IBM Plex Mono",
    vars: {
      "--nv-font-display": "'Mulish', system-ui, sans-serif",
      "--nv-font-body": "'Mulish', system-ui, sans-serif",
      "--nv-font-mono": "'IBM Plex Mono', ui-monospace, monospace",
      "--nv-display-tracking": "-0.015em",
    },
  },
];

/** Letter-spacing presets (studio) — space between letters. */
export const LETTER_SPACINGS = [
  { id: "tight", name: "Tight", vars: { "--nv-letter-spacing": "-0.02em" } },
  { id: "normal", name: "Normal", vars: { "--nv-letter-spacing": "0em" } },
  { id: "wide", name: "Wide", vars: { "--nv-letter-spacing": "0.03em" } },
];

/** Line-height presets (studio) — space between lines. */
export const LINE_HEIGHTS = [
  { id: "snug", name: "Snug", vars: { "--nv-line-height": "1.4" } },
  { id: "normal", name: "Normal", vars: { "--nv-line-height": "1.6" } },
  { id: "relaxed", name: "Relaxed", vars: { "--nv-line-height": "1.85" } },
];

/** Corner-radius presets (studio). Two mechanisms, applied together:
 *  1. Override Tailwind's named radius scale (`--radius-*`) → all `rounded-lg/xl/2xl…`.
 *  2. A unitless `--nv-r-scale` multiplier → the bespoke card radii, which are
 *     authored as `rounded-[calc(NNpx*var(--nv-r-scale,1))]`.
 *  "soft" = scale 1 + Tailwind defaults = today's look (no visual change). */
export const RADII = [
  {
    id: "sharp",
    name: "Sharp",
    vars: {
      "--nv-r-scale": "0.4",
      "--radius-sm": "2px", "--radius-md": "2px", "--radius-lg": "3px",
      "--radius-xl": "5px", "--radius-2xl": "6px", "--radius-3xl": "10px",
      "--radius-4xl": "13px",
    },
  },
  {
    id: "soft",
    name: "Soft",
    vars: {
      "--nv-r-scale": "1",
      "--radius-sm": "4px", "--radius-md": "6px", "--radius-lg": "8px",
      "--radius-xl": "12px", "--radius-2xl": "16px", "--radius-3xl": "24px",
      "--radius-4xl": "32px",
    },
  },
  {
    id: "round",
    name: "Round",
    vars: {
      "--nv-r-scale": "1.6",
      "--radius-sm": "6px", "--radius-md": "10px", "--radius-lg": "13px",
      "--radius-xl": "19px", "--radius-2xl": "26px", "--radius-3xl": "38px",
      "--radius-4xl": "51px",
    },
  },
];

/** Heading / body weight presets toggled in the studio (Light · Medium · Bold). */
export const WEIGHTS = [
  { id: "light", name: "Light", vars: { "--nv-weight-heading": "700", "--nv-weight-body": "400" } },
  { id: "medium", name: "Medium", vars: { "--nv-weight-heading": "800", "--nv-weight-body": "450" } },
  { id: "bold", name: "Bold", vars: { "--nv-weight-heading": "900", "--nv-weight-body": "500" } },
];

/** Device preview frames (px) used by the studio's responsive viewer.
 *  The real kiosk runs the tablet responsive view, so the portrait tablet
 *  frame doubles as the kiosk preview (carries the 3 layout variants). */
export const DEVICES = [
  { id: "live", name: "Live", icon: "monitor", w: null, h: null },
  { id: "phone", name: "Phone", icon: "smartphone", w: 390, h: 844 },
  { id: "tablet", name: "Tablet", icon: "tablet", w: 834, h: 1112 },
  { id: "desktop", name: "Desktop", icon: "monitor", w: 1280, h: 800 },
  // The physical unit: Apolosign 32" display mounted portrait (1080×1920).
  // Frames the page with ?kiosk= so the preview shows true kiosk mode.
  { id: "kiosk", name: "Kiosk 32″", icon: "monitor", w: 1080, h: 1920 },
];

/** Portrait tablet / kiosk homepage hero layouts. The studio drives the chosen
 *  variant onto the tablet preview via `?kiosk=<id>`; on a real tablet (or the
 *  kiosk's tablet view) the portrait breakpoint shows the same hero. */
export const KIOSK_LAYOUTS = [
  { id: "overlay", name: "Overlay Hero", tagline: "Headline over the full-width video, bigger goal list" },
  { id: "desktop", name: "Desktop Hero", tagline: "Same split layout as the desktop site" },
];

export const DEFAULTS = {
  palette: "slate",
  typography: "grotesk",
  weight: "medium",
  italic: false,
  letterSpacing: "normal",
  lineHeight: "normal",
  radius: "soft",
  device: "live",
  kioskLayout: "overlay",
};

export const byId = (list, id) => list.find((x) => x.id === id) || list[0];
